MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "http://storage.googleapis.com/public-models/efficientnet-b0-08094119.pth"
  RPN_ONLY: True
  RETINANET_ON: True
  BACKBONE:
    CONV_BODY: "EFNET-B0-FPN-RETINA"
    FREEZE_CONV_BODY_AT: -1
  EFNET:
    BN: 'GN'
  FPN:
    USE_GN: True
  RPN:
    USE_FPN: True
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    NMS_THRESH: 0.5
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  RETINANET:
    ANCHOR_STRIDES: (8, 16, 32)
    ANCHOR_SIZES: (13, 26, 52)
    ASPECT_RATIOS: (0.33, 1, 3)
    SCALES_PER_OCTAVE: 3
    STRADDLE_THRESH: -1
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    NUM_CLASSES: 80
    USE_C5: False
    NUM_CONVS: 4
  GROUP_NORM:
    NUM_GROUPS: 8
DATASETS:
  TRAIN: ("coco_icevision_train", "coco_RTSD_train")
  TEST: ("coco_icevision_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.004
  WEIGHT_DECAY: 0.0001
  STEPS: (40000, 80000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 6
  CHECKPOINT_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (608,)
  MAX_SIZE_TRAIN: 608
  MIN_SIZE_TEST: 608
  MAX_SIZE_TEST: 608
  PIXEL_MEAN: [120.17, 133.96, 143.09]
  PIXEL_STD: [73.27, 75.32 , 71.49]
TEST:
  RUN_HIRES: True
  HIRES_FROM: 650
  LOWRES_TO: 1216
  SCALE_FACTOR: 2
DTYPE: "float16"
OUTPUT_DIR: "./ice_model"
